config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/token' => "users#token"

  resources :collections

  namespace :api do
    resources :collections do
      resources :artworks
    end
  end

  resources :users, only: [:new, :create]
  get '/users/log_in' => "users#log_in", as: :log_in
  get '/users/profile' => "users#profile", as: :profile
  get '/users/profile/search' => "users#search", as: :search
  post '/sessions' => "sessions#create", as: :create_session
  delete '/sessions' => "sessions#destroy", as: :delete_session

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
    belongs_to :collection
end

app/models/collection.rb
class Collection < ActiveRecord::Base
    has_many :artworks, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :collections
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def index
    @user = current_user
  end

end

app/controllers/api/artworks_controller.rb
class Api::ArtworksController < ApplicationController

  include SessionsHelper

  # show all artworks in collection
  def index
    if params[:format] === "json"
      @user = current_user
      @collection = Collection.find params[:collection_id]
      @artworks = Artwork.where(collection_id: @collection.id)
      render json: @artworks
    else
      @user = current_user
      @collection = Collection.find params[:collection_id]
      @artworks = Artwork.where(collection_id: @collection.id)
      render :index
    end
  end

  def create
    new_artwork = Artwork.create artwork_params
    render json: {artworks: new_artwork }
  end


  def destroy
    @user = current_user
    artwork = Artwork.find params[:id]
    artwork.destroy
    redirect_to edit_collection_path artwork.collection_id
  end

  def set_deault
    @user = current_user
    collection = Collection.find params[:collection_id]
    artwork = Artwork.find params[:id]
    collection.default_image = artwork.thumbnail
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :url, :collection_id, :thumbnail)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  include SessionsHelper

  # show all collections for the user
  def index
    @user = current_user
    @collections = Collection.where(user_id: @user)
    render json: @collections
  end

  # show all public collections
  def all
    @collections = Collection.where(is_public: true)
  end

  # create a new collection
  def new
    @user = current_user
    @collection = Collection.new
  end

  #create
  def create
    @user = current_user
    new_collection = Collection.create collection_params.merge user_id: current_user.id
    redirect_to profile_path
  end

  def show
    if params[:format] === "json"
      @user = current_user
      @collection = Collection.find params[:id]
      @artworks = Artwork.where(collection_id: @collection.id)
    render json: @collection
    else
      @user = current_user
      @collection = Collection.find params[:id]
      @artworks = Artwork.where(collection_id: @collection.id)
      render :show
    end
  end

  #          PATCH  /travelers/:id(.:format)         travelers#update
  #          PUT    /travelers/:id(.:format)         travelers#update
  def edit
    @user = current_user
    @collection= Collection.find params[:id]
    @artworks = Artwork.where(collection_id: @collection.id)
  end

  def update
    @user = current_user
    collection = Collection.find params[:id]
    collection.update collection_params
    redirect_to collection_path collection.id
  end

  def destroy
    @user = current_user
    @collection = Collection.find params[:id]
    @collection.destroy
    redirect_to profile_path
  end

  private

    def collection_params
      params.require(:collection).permit(:title, :description, :is_private, :user_id, :default_image)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # take the username and password and confirm this is a user on the site
  def create
    #get the fields from the form
    name = params[:name]
    username = params[:username]
    password = params[:password]
    user = User.find_by username: username

    #user.authenticate becuase has_secure_password was included in the model
    if user && user.authenticate( password )
      session[:user_id] = user.id
      # should redirect to servers profile page
      redirect_to profile_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper

  require 'net/http'
  require 'json'

  before_action :authenticate!, only: [:profile]

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    redirect_to log_in_path
  end

  def log_in
    @user = current_user
  end

  def profile
    @user = current_user
    @your_collections = Collection.where(user_id: @user)
    @all_collections = Collection.where.not(user_id: @user)
    @all_collections  = @all_collections.where(is_private: false)
  end

  def search
    @user = current_user
    @collections = Collection.where(user_id: @user)
  end

  def token
    api_url = URI.parse('https://api.artsy.net/api/tokens/xapp_token')
    response = Net::HTTP.post_form(api_url, client_id: ENV['client_id'], client_secret: ENV['client_secret'])
    # binding.pry
    xapp_token = JSON.parse(response.body)['token']
    render json: { token: xapp_token }
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def authenticate!
    redirect_to log_in_path unless current_user
  end

  def current_user
    if session[:user_id]
      @current_user = User.find session[:user_id]
    end
  end

end

app/views/collections/edit.html.erb
<% if @user.id == @collection.user_id %>

  <%= form_for @collection, :html => {class: 'edit-form'} do |f| %>
    <br>
    <%= f.label :title, "TITLE" %>
    <br>
    <%= f.text_field :title, class: 'text-input'%>
    <br>
    <%= f.label :description, "DESCRIPTION" %>
    <br>
    <%= f.text_field :description, class: 'text-input' %>
    <br>
    <%= f.radio_button :is_private, true %>
    <%= label :is_private, "PRIVATE" %>
    <%= f.radio_button :is_private, false %>
    <%= label :is_private, "PUBLIC" %>
    <br>
    <%= f.submit "UPDATE", class: 'edit-btn' %>
    <% end %>

  <%= link_to "DELETE", collection_path(@collection), method: :delete, class: 'edit-btn' %>


  <div class="edit-collection-artwork-container">
    <% @artworks.each do |artwork| %>
      <div class="edit-collection-artwork">
        <img src="<%= artwork.thumbnail %>" class="edit-img" title="{{artwork.title}}">
        <!-- <p><%= artwork.title %></p> -->
        <br>
        <%= link_to "X", api_collection_artwork_path(artwork.collection_id, artwork.id), method: :delete,  class: "x-delete" %>
          <%= form_tag collection_path(@collection), method: "put" do %>
            <%= hidden_field_tag 'collection[default_image]', artwork.thumbnail %>
            <%= submit_tag "SET AS WALLPAPER", class: 'clear-btn wallpaper-btn' %>
          <% end %>

      </div>
    <% end %>
  </div>
<% end %>

app/views/collections/new.html.erb
<div class="new-collection">
<h3>new collection</h3>
<%= form_for @collection do |f| %>
  <%= f.label :title, "TITLE" %>
  <br>
  <%= f.text_field :title, class: 'text-input' %>
  <br>
  <%= f.label :description, "DESCRIPTION" %>
  <br>
  <%= f.text_field :description, class: 'text-input' %>
  <br>
  <%= f.radio_button :is_private, true %>
  <%= label :is_private, "PRIVATE" %>
  <%= f.radio_button :is_private, false %>
  <%= label :is_private, "PUBLIC" %>
  <br>
  <%= f.submit "CREATE", class: 'clear-btn' %>
<% end %>
</div>

app/views/collections/show.html.erb
<% if @user.id == @collection.user_id %>
  <h2>
    <%= @collection.title %>
    <!-- <h4><%= link_to "EDIT COLLECTION", edit_collection_path(@collection) %></h4> -->
    <%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_collection_path(@collection) %>
  </h2>
  <h4><%= @collection.description %></h4>
  <h6>curated by: @<%= @user.username %></h6>
  <div class="search">
    <%= link_to "<span class=\"glyphicon glyphicon-search\"></span>".html_safe, search_path %>
  </div>
<% else %>
  <h2><%= @collection.title %></h2>
  <h4><%= @collection.description %></h4>
  <div class="search">
    <%= link_to "<span class=\"glyphicon glyphicon-search\"></span>".html_safe, search_path %>
  </div>
<% end %>

<% if @artworks.blank? %>
  <div class="add-art">
    <%= link_to "ADD ART +".html_safe, search_path %>
  </div>
<% else %>
  <div id="collection-carousel" class="carousel slide">
    <% @artworks.each_with_index do |artwork, index| %>
      <ol class="carousel-indicators">
      <% if index == 0 %>
        <li data-target="#collection-carousel" data-slide-to="<%= artwork %>" class="active" ></li>
      <% else %>
        <li data-target="#collection-carousel" data-slide-to="<%= artwork %>" ></li>
      <% end %>
      </ol>
    <% end %>
    <div class="carousel-inner">
      <% @artworks.each_with_index do |artwork, index| %>
        <% if index == 0 %>
          <div class="item active">
            <img src="<%= artwork.thumbnail %>" class="car-img">
            <div class="carousel-caption">
              <p><%= artwork.title %></p>
            </div>
          </div>
        <% else %>
          <div class="item">
            <img src="<%= artwork.thumbnail %>" class="car-img">
            <div class="carousel-caption">
              <p><%= artwork.title %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <a class="left carousel-control" href="#collection-carousel" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#collection-carousel" data-slide="next">
      <span class="icon-next"></span>
    </a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="MyApp">
  <head>
    <title>WhitespaceApp</title>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <header>
        <meta name="viewport" content="width=device-width, initial-scale=1">
  </header>
  <body>
    <div class="container">
      <% if !current_user %>
        <h1><%= link_to "whitespace", root_path, { :class=>"logo" } %></h1>
        <div class = "log-in">
          <h5><%= link_to "sign up", new_user_path %> // <%= link_to "log in", log_in_path %></h5>
        </div>
      <% else %>
        <h1><%= link_to "whitespace", profile_path, { :class=>"logo" } %></h1>
        <div class = "log-out">
          <%= link_to "<span class=\"glyphicon glyphicon-log-out\"></span>".html_safe, delete_session_path, method: :delete %>
          <!-- <h5><%= link_to '<i class="glyphicon glyphicon-log-out"></i>', delete_session_path, method: :delete %></h5> -->
        </div>
        <div class="search">
          <%= link_to "<span class=\"glyphicon glyphicon-search\"></span>".html_safe, search_path %>
        </div>
        <div class="add-collection">
        <!-- <h4><%= link_to "CREATE NEW COLLECTION", new_collection_path %></h4> -->
          <%= link_to "<span class=\"glyphicon glyphicon-plus\"></span>".html_safe, new_collection_path %>
        </div>




      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/log_in.html.erb
<div class="log-in-form">

<h3>log in</h3>

<%= form_tag '/sessions', method: :post do %>
  <%= label_tag :username, "USERNAME"  %>
  <br>
  <%= text_field_tag :username, nil, class: 'sign-up-input' %>
  <br>
  <%= label_tag :password , "PASSWORD" %>
  <br>
  <%= password_field_tag :password,  nil, class: 'sign-up-input'  %>
  <br>
  <%= submit_tag("LOG IN",  :class=>'clear-btn wallpaper-btn form-btn') %>
<% end %>
<p>don't have an account? <%= link_to "sign up", new_user_path %></p>
</div>

app/views/users/new.html.erb
<div class="sign-up-form">
<h3>sign up</h3>

<%= form_for @user do |f| %>

  <%= f.label :username, "USERNAME" %>
  <br>
  <%= f.text_field :username, class: 'sign-up-input' %>
  <br>
  <%= f.label :password, "PASSWORD" %>
  <br>
  <%= f.password_field :password, class: 'sign-up-input'%>
  <br>
  <%= f.label :password_confirmation, "PASSWORD CONFIRMATION" %>
  <br>
  <%= f.password_field :password_confirmation, class: 'sign-up-input' %>
  <br>
  <%= f.submit "SIGN UP", class: 'clear-btn form-btn' %>
<% end %>
</div>

app/views/users/profile.html.erb
<div class="collection-type">YOUR COLLECTIONS</div>
<div class="collection-container">
  <% @your_collections.reverse_each do |collection| %>
    <%= link_to collection_path(collection.id) do %>
      <div class="collection" style="background-image: url('<%= collection.default_image %>');">
        <%= collection.title %>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<div class="collection-type">EXPLORE COLLECTIONS</div>
<div class="collection-container">
  <% @all_collections.reverse_each do |collection| %>
    <%= link_to collection_path(collection.id) do %>
      <div class="collection" style="background-image: url('<%= collection.default_image %>');">
        <%= collection.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/search.html.erb
<div ng-controller="ArtworksController">
  <form class="search-form">
    <input ng-model="term" id="search-box" placeholder="Search...">
    <button type="button" ng-click="search(term)"><span class="glyphicon glyphicon-search searchbar-icon"></span></button>
  </form>
  <br>


  <div ng-repeat="artwork in artworks" class="search-results-container">
    <div class="search-result">
      <img src= "{{artwork.thumbnailImage}}" title="{{artwork.title}}">
      <!-- <p>{{artwork.title}}</p> -->
      <br>
      <a ng-click="addForm = !addForm">
        <div class="plus">+</div>
      </a>

      <div class="add-form" ng-show="addForm">
        <label for="mySelect">SELECT COLLECTION:</label>
        <br>
        <select name="mySelect" id="mySelect"
          ng-options="collection.title for collection in collections"
          ng-model="data.selectedOption"></select>
          <button name="button" ng-click="saveArt(artwork, data.selectedOption.id); addForm = !addForm" class="clear-btn">SAVE</button>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="splash">
  <h2>welcome to whitespace</h2>
  <h4>a place to curate and share original art collections</h4>
</div>